packages:
  - 'apps/backend/*'
  - 'apps/frontend/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  bcrypt: true
  msgpackr-extract: true
  oracledb: true
  sqlite3: true
  unrs-resolver: true
