services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - ..:/workspace:cached
    networks:
      - hsm-app-network
    env_file:
      - ../.env
    command: sleep infinity
