### Signup
POST {{host}}/auth/signup
Content-Type: {{contentType}}

{
  "username": "rsantamaria",
  "password": "RSFutbol2001@",
  "firstName": "Raul",
  "firstLastName": "Santamaria",
  "email": "rsantamariao@hospitalsantamaria.com.ec",
  "phoneNumber": "+593969883869",
  "gender": "male",
  "roles": ["admin"]
}

### Log in
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
  "username": "rsantamaria",
  "password": "RSFutbol2001@"
}

### Logout
GET {{host}}/auth/logout
Authorization: Bearer {{token}}

### Profile
GET {{host}}/auth/profile
Authorization: Bearer {{token}}

### Refresh
GET {{host}}/auth/refresh
Authorization: Bearer {{token}}

### Signup Integration Token
POST {{host}}/auth/signup/integration
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "name": "raul",
  "description": "test",
  "functionality": "dev"
}

### Logout Integration Token
POST {{host}}/auth/logout/integration
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "token": "<integration-token>"
}

### Generate PIN
POST {{host}}/auth/pin/generate
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "purpose": "email_verification",
  "target": "example@example.com"
}

### Validate PIN
POST {{host}}/auth/pin/validate
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "purpose": "email_verification",
  "target": "example@example.com",
  "code": 123456
}
