export enum EmailWebhookEventTypeEnum {
  DELIVERED = 'DELIVERED',
  OPEN = 'OPEN',
  CLICK = 'CLICK',
  BOUNCE = 'BOUNCE',
  HARD_BOUNCE = 'HARD_BOUNCE',
  SOFT_BOUNCE = 'SOFT_BOUNCE',
  SPAM = 'SPAM',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
  DEFERRED = 'DEFERRED',
  INVALID_EMAIL = 'INVALID_EMAIL',
}
